import fs from "node:fs";
import path from "node:path";
import { instructionsFor, scoreLabels } from "./questions.js";
import type { Candidate, DecisionField } from "./types.js";

const DEFAULT_THRESHOLD = 0.7;

/** Score fields with no description: the generated question has to guess which end of the scale is high. */
function unscaledScores(c: Candidate): string[] {
  return c.fields.filter((f) => f.kind === "score" && !f.description).map((f) => f.name);
}

const scaleNote = (c: Candidate, comment: string) => {
  const names = unscaledScores(c);
  return names.length
    ? `${comment} CHECK THE SCALE: ${names.join(", ")} had no description, so the question guesses which end is highest.\n${comment} State what the ends mean (e.g. "1 = low, 5 = critical") to match your LLM, or agreement will be low.\n`
    : "";
};

/** One warning per candidate whose score fields have no description. */
export function scaleWarnings(candidates: Candidate[]): string[] {
  return candidates.flatMap((c) => {
    const names = unscaledScores(c);
    return names.length
      ? [`${c.id}: score field${names.length > 1 ? "s" : ""} ${names.join(", ")} ha${names.length > 1 ? "ve" : "s"} no description, so the generated question guesses which end of the scale is highest. Edit it to say what the ends mean (e.g. "1 = low, 5 = critical"), matching your LLM prompt.`]
      : [];
  });
}

function questionCode(c: Candidate, f: DecisionField): string {
  const ins = JSON.stringify(instructionsFor(c, f));
  if (f.kind === "choice") {
    const crit = f.options.map((o) => `${JSON.stringify(o)}: null`).join(", ");
    return `  ${f.name}: choice(${ins}, { ${crit} }),`;
  }
  if (f.kind === "noul") return `  ${f.name}: noul(${ins}),`;
  return `  ${f.name}: score(${ins}, ${JSON.stringify(scoreLabels(f))}),`;
}

function typeCode(f: DecisionField): string {
  if (f.kind === "choice") return `  ${f.name}: ${f.options.map((o) => JSON.stringify(o)).join(" | ")};`;
  if (f.kind === "noul") return `  ${f.name}: boolean;`;
  return `  ${f.name}: number; // ${f.min}..${f.max}`;
}

function valueCode(f: DecisionField): string {
  if (f.kind === "choice") return `    ${f.name}: a.${f.name}.choice,`;
  if (f.kind === "noul") return `    ${f.name}: a.${f.name}.noul >= 0.5,`;
  return `    ${f.name}: ${f.min} + Math.round(a.${f.name}.score),`;
}

function confCode(f: DecisionField): string {
  // Noul answers carry no confidence field; derive one from distance to 0.5.
  return f.kind === "noul" ? `Math.abs(a.${f.name}.noul - 0.5) * 2` : `a.${f.name}.confidence`;
}

export function generateModule(c: Candidate): string {
  const kinds = [...new Set(c.fields.map((f) => f.kind))].sort();
  const dropped = c.droppedFields.length
    ? `\n// NOTE: dropped non-decision fields (Jev does not generate text): ${c.droppedFields.join(", ")}.\n// Check nothing downstream depends on them before switching.\n`
    : "";
  return `// Generated by jev-swap from ${c.file}:${c.line} (${c.provider} ${c.api}, detected via ${c.signal}).
// Review each question: Jev works best with one short, gut-check question per field.${dropped}
${scaleNote(c, "//")}
import { TypeSafeClient, ${kinds.join(", ")}, type EntryType } from "@typesafe-ai/sdk";

const client = new TypeSafeClient(); // reads TYPESAFE_API_KEY

/** Minimum decision confidence to act on Jev's answer. Updated by \`jev-swap shadow\` (real runs only). */
export const THRESHOLD = ${DEFAULT_THRESHOLD};

export const questions = {
${c.fields.map((f) => questionCode(c, f)).join("\n")}
} as const;

export type Decision = {
${c.fields.map(typeCode).join("\n")}
};

/**
 * State for this call. Original prompt inputs: ${c.stateExprs.length ? c.stateExprs.join(", ") : "(none detected)"}.
 * Pass the raw input (string or object), not the full LLM prompt.
 */
export async function decide(state: EntryType) {
  const res = await client.systemOne({ state, questions });
  const a = res.answers;
  const value: Decision = {
${c.fields.map(valueCode).join("\n")}
  };
  const confidence = Math.min(${c.fields.map(confCode).join(", ")});
  return { value, confidence, raw: res };
}

/** Hybrid: use Jev when confident, otherwise fall back to the existing LLM call. */
export async function decideWithFallback(
  state: EntryType,
  llmFallback: () => Promise<Decision>,
  threshold = THRESHOLD,
): Promise<Decision & { source: "jev" | "llm" }> {
  try {
    const d = await decide(state);
    if (d.confidence >= threshold) return { ...d.value, source: "jev" };
  } catch {
    // Jev unavailable: fall through to the LLM.
  }
  return { ...(await llmFallback()), source: "llm" };
}
`;
}

// ---------- Python (typesafe-sdk) ----------

const PY_CLASS = { choice: "Choice", noul: "Noul", score: "Score" } as const;
const PY_GROUP = { choice: "choices", noul: "nouls", score: "scores" } as const;

function pyQuestion(c: Candidate, f: DecisionField): string {
  const ins = JSON.stringify(instructionsFor(c, f));
  if (f.kind === "choice") {
    const crit = f.options.map((o) => `${JSON.stringify(o)}: None`).join(", ");
    return `    ${JSON.stringify(f.name)}: Choice(instructions=${ins}, criteria={${crit}}),`;
  }
  if (f.kind === "noul") return `    ${JSON.stringify(f.name)}: Noul(instructions=${ins}),`;
  return `    ${JSON.stringify(f.name)}: Score(instructions=${ins}, criteria=${JSON.stringify(scoreLabels(f))}),`;
}

function pyType(f: DecisionField): string {
  if (f.kind === "choice") return `    ${f.name}: Literal[${f.options.map((o) => JSON.stringify(o)).join(", ")}]`;
  if (f.kind === "noul") return `    ${f.name}: bool`;
  return `    ${f.name}: int  # ${f.min}..${f.max}`;
}

function pyAnswer(f: DecisionField): string {
  return `res.${PY_GROUP[f.kind]}[${JSON.stringify(f.name)}]`;
}

function pyValue(f: DecisionField): string {
  const a = pyAnswer(f);
  if (f.kind === "choice") return `        ${JSON.stringify(f.name)}: ${a}.choice,`;
  if (f.kind === "noul") return `        ${JSON.stringify(f.name)}: ${a}.noul >= 0.5,`;
  // score is >= 0, so int(x + 0.5) rounds half up (Python's round() is banker's rounding).
  return `        ${JSON.stringify(f.name)}: ${f.min} + int(${a}.score + 0.5),`;
}

function pyConf(f: DecisionField): string {
  return f.kind === "noul" ? `abs(${pyAnswer(f)}.noul - 0.5) * 2` : `${pyAnswer(f)}.confidence`;
}

export function generatePythonModule(c: Candidate): string {
  const kinds = [...new Set(c.fields.map((f) => PY_CLASS[f.kind]))].sort();
  const needsLiteral = c.fields.some((f) => f.kind === "choice");
  const dropped = c.droppedFields.length
    ? `# NOTE: dropped non-decision fields (Jev does not generate text): ${c.droppedFields.join(", ")}.\n# Check nothing downstream depends on them before switching.\n`
    : "";
  return `# Generated by jev-swap from ${c.file}:${c.line} (${c.provider} ${c.api}, detected via ${c.signal}).
# Review each question: Jev works best with one short, gut-check question per field.
${dropped}${scaleNote(c, "#")}from __future__ import annotations

from typing import Callable${needsLiteral ? ", Literal" : ""}, TypedDict, cast

from typesafe_sdk import ${[...kinds, "JSONContent", "Question", "TypeSafeClient"].join(", ")}

client = TypeSafeClient()  # reads TYPESAFE_API_KEY

# Minimum decision confidence to act on Jev's answer. Updated by \`jev-swap shadow\` (real runs only).
THRESHOLD = ${DEFAULT_THRESHOLD}

QUESTIONS: dict[str, Question] = {
${c.fields.map((f) => pyQuestion(c, f)).join("\n")}
}


class Decision(TypedDict):
${c.fields.map(pyType).join("\n")}


def decide(state: JSONContent) -> tuple[Decision, float]:
    """State for this call. Original prompt inputs: ${c.stateExprs.length ? c.stateExprs.join(", ") : "(none detected)"}.

    Pass the raw input (str or dict), not the full LLM prompt.
    """
    res = client.system_one(state=state, questions=QUESTIONS)
    value = cast(Decision, {
${c.fields.map(pyValue).join("\n")}
    })
    confidence = ${c.fields.length === 1 ? pyConf(c.fields[0]) : `min(${c.fields.map(pyConf).join(", ")})`}
    return value, confidence


def decide_with_fallback(
    state: JSONContent,
    llm_fallback: Callable[[], Decision],
    threshold: float = THRESHOLD,
) -> tuple[Decision, str]:
    """Hybrid: use Jev when confident, otherwise fall back to the existing LLM call."""
    try:
        value, confidence = decide(state)
        if confidence >= threshold:
            return value, "jev"
    except Exception:
        pass  # Jev unavailable: fall through to the LLM.
    return llm_fallback(), "llm"
`;
}

function sampleTemplate(c: Candidate): string {
  const llm = Object.fromEntries(c.fields.map((f) => [f.name, f.kind === "choice" ? f.options[0] : f.kind === "noul" ? true : f.min]));
  return JSON.stringify({ candidate: c.id, state: "<raw input the LLM saw>", llm, llm_usage: { input_tokens: 0, output_tokens: 0 } });
}

export function convert(candidates: Candidate[], outDir: string): string[] {
  const jevDir = path.join(outDir, "jev");
  fs.mkdirSync(jevDir, { recursive: true });
  const written: string[] = [];
  for (const c of candidates) {
    const py = c.language === "python";
    const p = path.join(jevDir, py ? `${c.id.replace(/[^\w]/g, "_")}.py` : `${c.id}.ts`);
    fs.writeFileSync(p, py ? generatePythonModule(c) : generateModule(c));
    written.push(p);
  }
  fs.writeFileSync(path.join(outDir, "samples.template.jsonl"), candidates.map(sampleTemplate).join("\n") + "\n");
  return written;
}

/** Write a threshold into a candidate's generated module (.ts or .py). Returns the file written, if any. */
export function applyThreshold(outDir: string, id: string, threshold: number): string | undefined {
  const ts = path.join(outDir, "jev", `${id}.ts`);
  const py = path.join(outDir, "jev", `${id.replace(/[^\w]/g, "_")}.py`);
  if (fs.existsSync(ts)) {
    fs.writeFileSync(ts, fs.readFileSync(ts, "utf8").replace(/export const THRESHOLD = [\d.]+;/, `export const THRESHOLD = ${threshold};`));
    return ts;
  }
  if (fs.existsSync(py)) {
    fs.writeFileSync(py, fs.readFileSync(py, "utf8").replace(/^THRESHOLD = [\d.]+$/m, `THRESHOLD = ${threshold}`));
    return py;
  }
  return undefined;
}
